<?xml version="1.0"?>
<!-- #机器人的名字{1网址作用:用了xacro这个弘语言了} -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<!-- 声明质量与惯性属性部分（因为要在 bask_link 中用质量与惯性属性部分） -->
<xacro:include filename="$(find fishbot_description)/urdf/fishbot/common_inertia.xacro"/>

    <!-- 声明一个弘base -->
    <xacro:macro name="base_xacro" params="length radius">
        <!-- 添加虚拟部件 -->
        <link name="base_footprint" />  

        <link name="base_link">
            <!-- 机器人部件的外观描述 -->
            <visual>
                <!-- 沿着自己几何中心的偏移和旋转量 -->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <!-- 几何形状 -->
                <geometry>
                    <!--  正方体长宽高 -->
                    <!-- <box size="0.0 0.0 0.0"/> -->
                    <!-- 圆柱体 半径m，高度m -->
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <!-- 材质，颜色红绿蓝（0.0-1.0）透明度（半透明1.0表示不透明） -->
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </visual>
            <!-- 添加碰撞属性 -->
            <collision>
                <!-- 沿着自己几何中心的偏移和旋转量 -->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <!-- 几何形状 -->
                <geometry>
                    <!--  正方体长宽高 -->
                    <!-- <box size="0.0 0.0 0.0"/> -->
                    <!-- 圆柱体 半径m，高度m -->
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <!-- 材质，颜色红绿蓝（0.0-1.0）透明度（半透明1.0表示不透明） -->
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </collision>

            <xacro:cylinder_inertia m="1.0" r="${radius}" h="${length}" />
        </link>

        <joint name="joint_name" type="fixed">
            <origin xyz="0.0 0.0 ${length/2.0+0.032-0.001}" rpy="0.0 0.0 0.0"/>
            <parent link="base_footprint"/>
            <child link="base_link"/>
        </joint>
    </xacro:macro>
</robot>

<!-- xacro不能直接用,必须得转成urdf才能用 -->